sudo: required
services:
    - docker

before_install:
    - docker image build -t limozaza/docker-react -f Dockerfile.dev .

script:
    - docker container run -e CI=true limozaza/docker-react npm run test

    # - docker run -e CI=true USERNAME/docker-react npm run test